# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 10:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
        ('api', '0002_authtoken_user'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=django.contrib.postgres.fields.citext.CIEmailField(max_length=511, unique=True, verbose_name='Email address'),
        ),
    ]
